console.log(document.querySelectorAll(".lyrics"))
console.log(document.getElementsByClassName("lyrics"))
const title = document.getElementById("song-title")
console.log(title)

console.log(title.textContent)
console.log(title.innerText)
console.log(title.className)
console.log(title.style)
console.log(title.title)