# Generated by Django 5.0.1 on 2024-01-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('link', models.URLField(verbose_name='링크')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크  목록',
            },
        ),
    ]
